# Ime pipeline-a za backend
name: Backend CI/CD

# Dogodki, ki sprožijo workflow (push in pull request na glavno vejo)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job za gradnjo backenda
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Kloniranje repozitorija
        uses: actions/checkout@v3

      - name: Setup Node.js  # Namestitev Node.js okolja
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Spremenite glede na vašo različico Node.js

      - name: Cache node_modules  # Caching odvisnosti
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install dependencies  # Namestitev odvisnosti
        run: |
          cd backend
          npm ci

      - name: Upload backend artifacts  # Naložitev artefaktov za backend
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: |
            backend/
            backend/node_modules/

  # Job za testiranje backenda
  test-backend:
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  # Kloniranje repozitorija
        uses: actions/checkout@v3

      - name: Setup Node.js  # Namestitev Node.js okolja
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules  # Caching odvisnosti
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install dependencies  # Namestitev odvisnosti
        run: |
          cd backend
          npm install

      - name: Run specific tests  # Izvajanje specifične datoteke s testi
        run: |
          cd backend
          npm test -- tests/app.test.js --coverage  # Izvedi samo združeno datoteko
        # Če uporabljate `jest`, lahko definirate natančno datoteko, ki jo želite testirati.

      - name: Upload coverage report  # Naložitev poročila o pokritosti kode
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage/
