# Ime pipeline-a za backend
name: Backend CI

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main

jobs:
  # Ime job-a za testiranje backenda
  test-backend:
    runs-on: ubuntu-latest  # Okolje, v katerem bo job tekel

    steps:
      - name: Checkout code  # Kloniranje repozitorija
        uses: actions/checkout@v3

      - name: Setup Node.js  # Namestitev Node.js okolja
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies  # Namestitev odvisnosti
        run: |
          cd backend
          npm install

      - name: Run tests with coverage  # Izvajanje testov s pokritostjo
        run: |
          cd backend
          npm run test:ci

      - name: Upload coverage report  # Naložitev poročila o pokritosti
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage/

  # Gradnja Docker slike in nalaganje na Docker Hub - Development
  dockerize-and-push-dev:
    needs: test-backend
    runs-on: ubuntu-latest
    environment: Development
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rirs:dev -t ${{ secrets.DOCKER_USERNAME }}/rirs:latest ./backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/rirs:dev ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rirs:dev
          docker push ${{ secrets.DOCKER_USERNAME }}/rirs:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rirs:${{ github.sha }}

  # Gradnja Docker slike in nalaganje na Docker Hub - Production
  dockerize-and-push-prod:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    environment:
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rirs:prod -t ${{ secrets.DOCKER_USERNAME }}/rirs:latest ./backend
          docker tag ${{ secrets.DOCKER_USERNAME }}/rirs:prod ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/rirs:prod
          docker push ${{ secrets.DOCKER_USERNAME }}/rirs:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/rirs:${{ github.sha }}
